// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX9tEnBnFxyFdmSUNXJnh6pMQ4f3_ul7U',
    appId: '1:784717932323:web:94ad6359f4ed5fa8810e96',
    messagingSenderId: '784717932323',
    projectId: 'flutterbase-bfe8f',
    authDomain: 'flutterbase-bfe8f.firebaseapp.com',
    storageBucket: 'flutterbase-bfe8f.appspot.com',
    measurementId: 'G-K2WPF7NGRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3fMPma4J7a-bETdxxRGYpepwkfEPCYiY',
    appId: '1:784717932323:android:28e8fd1e99de2979810e96',
    messagingSenderId: '784717932323',
    projectId: 'flutterbase-bfe8f',
    storageBucket: 'flutterbase-bfe8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-2Jo6sqCRIuUozmI0wFR90rQJ5RuBl4g',
    appId: '1:784717932323:ios:2df5b87eb2f33ded810e96',
    messagingSenderId: '784717932323',
    projectId: 'flutterbase-bfe8f',
    storageBucket: 'flutterbase-bfe8f.appspot.com',
    iosBundleId: 'com.example.flutterApplication13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX9tEnBnFxyFdmSUNXJnh6pMQ4f3_ul7U',
    appId: '1:784717932323:web:1230c5b6d33a1d0d810e96',
    messagingSenderId: '784717932323',
    projectId: 'flutterbase-bfe8f',
    authDomain: 'flutterbase-bfe8f.firebaseapp.com',
    storageBucket: 'flutterbase-bfe8f.appspot.com',
    measurementId: 'G-YRSE0LQN20',
  );
}
